namespace tests\obj;

class TestException extends Exception {
    public function __construct($message) {
        parent::__construct($message);
    }
}

class Err {
    public function one(){
        $this->two();
    }

    public function two(){
        throw new TestException('8888');
    }
}

try {
    $obj = new Err();
    $a = $obj->one();
} catch (Exception $e) {
    $msg = $e->getMessage();
    if ($msg != '8888') {
        Log::fatal('自定义异常抛出 error');
    } else {
        Log::info('自定义异常抛出成功');
    }
}
