<?php

// 测试 try-catch 语句
Log::info("开始测试 try-catch 语句");

// 测试基本的 try-catch
try {
    Log::info("执行 try 块");
    throw new Exception("测试异常");
} catch (Exception $e) {
    Log::info("捕获到异常: " . $e->getMessage());
}

// 测试 try-catch-finally
try {
    Log::info("执行 try 块（带 finally）");
    throw new Exception("另一个测试异常");
} catch (Exception $e) {
    Log::info("捕获到异常: " . $e->getMessage());
} finally {
    Log::info("执行 finally 块");
}

// 测试多个 catch 块
try {
    Log::info("执行 try 块（多个 catch）");
    throw new Exception("多 catch 测试异常");
} catch (Exception $e) {
    Log::info("第一个 catch 块: " . $e->getMessage());
} catch (Error $e) {
    Log::info("第二个 catch 块: " . $e->getMessage());
} finally {
    Log::info("执行 finally 块");
}

// 测试没有异常的 try 块
try {
    Log::info("执行没有异常的 try 块");
    $result = 1 + 1;
    Log::info("计算结果: " . $result);
} catch (Exception $e) {
    Log::fatal("不应该执行到这里");
} finally {
    Log::info("执行 finally 块（无异常）");
}

Log::info("try-catch 语句测试完成");